server:
  port: 8383

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  application:
    name: python
  main:
    allow-bean-definition-overriding: true

sidecar:
  # 异构微服务的IP
  ip: 127.0.0.1
  # 异构微服务的端口
  port: 9999

  # 异构微服务的健康检查URL
  #health-check-url: http://localhost:8080/health.json
management:
  endpoint:
    health:
      show-details: always

