server:
  port: 8585

spring:
  application:
    name: java-gateway #服务名称

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848                       # nacos 服务器地址
        service: ${spring.application.name}           # 注册到nacos的服务名

    gateway:
      discovery:
        locator:
          enabled: true   # 开启从注册中心动态创建路由的功能，利用微服务名进行路由

      routes:
        - id: nodejs                  # 路由id，保持唯一，尽量配合服务命名
          uri: lb://nodejs-consumer  # 匹配后提供服务的路由地址
          predicates:                 # 断言，路径匹配的进行路由
            - Path=/nodejs/**
        - id: python                  # 路由id，保持唯一，尽量配合服务命名
          uri: lb://python-consumer         # 匹配后提供服务的路由地址
          predicates:               # 断言，路径匹配的进行路由
            - Path=/python/**


logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG
